POST http://127.0.0.1:3000/auth/register
Content-Type: application/json

{
    "name": "nueva",
    "mail":"GFP@gmail.com",
    "password": "123456789",
    "telefono":"0987654321"
}

###################
POST http://127.0.0.1:3000/auth/login
Content-Type: application/json

{
    "name": "nue",
    "email":"GFP@gmail.com",
    "password": "123456789"
}

####
GET http://127.0.0.1:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkdGUEBnbWFpbC5jb20iLCJpZCI6MywiaWF0IjoxNzE4NTczNjAzLCJleHAiOjE3MTg1NzQyMDh9.Ios0vx5YnbS_l0Mv1g60ZLidEGPVxOYiB_mfRU6UrzE

#####
GET http://127.0.0.1:3000/categoria

################
POST http://127.0.0.1:3000/admin/categoria
Content-Type: application/json

{
    "nombreCategoria": "json",
    "detalle": "xdxd"
}